Исправил ошибки pre-commit
bullbesh/persistence pull request #19
Opened 2021-07-29 15:33 UTC by bullbesh

Исправил ошибки, выявленные через pre-commit в двух файлах (`main.py` и `keyboard.py`)
## Кратко об изменениях

Написал докстринги, где нужно, сократил количество символов на строке до позволенного, убрал неиспользуемые в работе объекты, переименовал одинаково записанные переменные
## Обоснование

Изменения нужны для приведения кода в единый стиль написания - PEP8
## Подробности

При попытке сделать какой-либо коммит в вышеупомянутых файлах вылезало море ошибок (особенно, в `main.py`), для дальнейшего написания кода или исправления старого я убрал все эти ошибки. Также остались некоторые недоработки в коммитах (надеюсь на фидбек и дальнейшее их дополнение)
## Необходимое пояснение

Документация единого стиля написания кода: https://www.python.org/dev/peps/pep-0008/

2021-07-29 16:24 UTC, Masynchin commented on persistence/main.py
> +    """Класс с капиталами и репортами"""
Немного странные докстринги, я в своём репозитории filogram и иначе сделал, советую посмотреть как

2021-07-29 16:30 UTC, Masynchin commented on persistence/keyboard.py
> +путем вызова клавиатур
За взаимодействие с пользователем, а уж тем более вызов клавиатур, отвечает main.py

2021-07-29 16:31 UTC, Masynchin commented on persistence/keyboard.py
> +(при использовании одной из функций бота)
Не нужно такие формулировки делать, просто "Города для поиска вакансий"

2021-07-29 16:33 UTC, Masynchin commented on persistence/keyboard.py
> +"""Клавиатуры (...)"""
А вообще, с фига тут докстринги? Она должна быть в описании модуля, функции и класса. Про клавы в модульной доке написано, значит тут не надо

2021-07-29 16:35 UTC, Masynchin commented on persistence/main.py
> +(...)
Добавлять нечего, думаю. Только разве что после информации тире и перечисление - финансы, текстовые данные, вакансии. Что-то типо такого

2021-07-29 16:36 UTC, Masynchin commented on persistence/main.py
> +    потенциальное ознакомление с его функциями
Уберите кинетику из описания

2021-07-29 16:37 UTC, Masynchin commented on persistence/main.py
> +        "Для ознакомления с функциями "
Вот тут красиво сделано, давно хотелось именно так :+1:

2021-07-29 16:37 UTC, Masynchin commented on persistence/main.py
> +    """Отправка извинения при вызове помощи"""
То, что на функции стоит заглушка, не позволяет писать такие докстринги. Опишите её так, как если бы она делала то, что должна

2021-07-29 16:39 UTC, Masynchin commented on persistence/main.py
> +    "Финансовая отчётность компании"
Думаю, что лучше такой стиль:
```
... со следующими функциями:
- Функция 1
- Функция 2
```
Это же и к другим схожим относится

2021-07-29 16:40 UTC, Masynchin commented on persistence/main.py
> +    стратегию и стратегические приоритеты, руководство)
Разбить, как сделано выше

2021-07-29 16:41 UTC, Masynchin commented on persistence/main.py
> +    """Северсталь Российская сталь"""
Исправить - начать с глагола/отглагольного существительного (как у вас выше "Отправка")

2021-07-29 16:41 UTC, Masynchin commented on persistence/main.py
> +    """Северсталь Ресурс"""
То же, что и выше

2021-07-29 16:42 UTC, Masynchin commented on persistence/main.py
> +    """Ключевые активы компании"""
То же, что и выше

2021-07-29 16:42 UTC, Masynchin commented on persistence/main.py
> +    """Торговые компании"""
То же, что и выше

2021-07-29 16:42 UTC, Masynchin commented on persistence/main.py
> +    """Предприятия дальнейшего передела"""
То же, что и выше

2021-07-29 16:42 UTC, Masynchin commented on persistence/main.py
> +    """Предприятия, имеющие какое-либо отношение к Северстали"""
То же, что и выше

2021-07-29 16:43 UTC, Masynchin commented on persistence/main.py
> +    """
Разбивка

2021-07-29 16:44 UTC, Masynchin commented on persistence/main.py
> +    принципа работы бота и краткое описание его функций
Лучше разбить надвое - кратко (Отправка помощи) и подробно (Отправляем то-то то-то)

2021-07-29 16:45 UTC, Masynchin commented on persistence/main.py
> +    """
Обработка нераспознанного сообщения. _Подробная секция_ - Отправляем то-то то-то

2021-07-29 16:49 UTC, bullbesh commented on persistence/main.py
> +    """Отправка извинения при вызове помощи"""
а я что сделал?

2021-07-29 16:59 UTC, Masynchin approved these changes
Все комменты исправить - аппрув. Надеюсь на честность

2021-07-30 00:14 UTC, bullbesh commented
> Все комменты исправить - аппрув. Надеюсь на честность

Жду итоговый вердикт, а не аппрувы на честность. Как только будет аппрув аппрува - сразу мержу

2021-07-30 03:58 UTC, Masynchin commented on persistence/main.py
> +    """Класс с капиталами и репортами"""
Так и не исправлено. Посмотрите, как [тут](https://github.com/Masynchin/filogram/blob/fd15bb42c32ffc942b824fb000663081c33d46aa/filogram/bot.py#L32) написано, явно видно, что это состояние, а не какой-то отдельный класс

2021-07-30 03:59 UTC, Masynchin commented on persistence/keyboard.py
> +"""
Мне кажется, лучше что-то типа "Кнопки-константы и клавиатуры для бота", без слова "модуль"

2021-07-30 04:02 UTC, Masynchin commented on persistence/main.py
> +- Помощь
"Сам бот - отправляет пользователю [то-то, то-то, то-то, и через запятую, кмк лучше]"

2021-07-30 04:08 UTC, Masynchin commented on persistence/main.py
> +    посмотреть все возможные варианты можно в файле keyboard.py
Именно тут не надо писать конкретные направления, просто "Пользователь выбирает направление вакансии, а потом город, и получает вакансии по данным критериях", про "существуют" вообще выкинуть надо. И упоминание, где смотреть тоже, сегодня есть там, завтра (условно, хотя недалеко от истины) там нет. Ну и точка - после первой секции нет, после второй есть, я за точки везде, кроме последнего. Если ставить точки везде, тогда я за везде

2021-07-30 04:08 UTC, Masynchin commented on persistence/main.py
> +    """
То же, что и выше

2021-07-30 04:09 UTC, Masynchin commented on persistence/main.py
> +    """
Команда старт на две строчки выше объявлена, лучше убрать из доки

2021-07-30 04:10 UTC, Masynchin commented on persistence/main.py
>          "нажмите на кнопку 'Помощь'",
Не увидел эту строку. Чего её со второй не объединил? Будет лучше выглядеть

2021-07-30 04:11 UTC, Masynchin commented on persistence/main.py
> +    """Отправка извинения при вызове помощи"""
Хрень ты сделал. Ну какое ещё, (брань), извинение при команде помощь? /help помощь должно выводить

2021-07-30 04:17 UTC, Masynchin commented
Я категорически против отсутствия точек. Это плохо выглядит и мешает читать, я привык, что так заканчивается текст, а тут ещё предложения. Я понимаю в самом конце не ставить, но не ставить в середине - :-1:

2021-07-30 04:19 UTC, Masynchin commented
> Я категорически против отсутствия точек. Это плохо выглядит и мешает читать, я привык, что так заканчивается текст, а тут ещё предложения. Я понимаю в самом конце не ставить, но не ставить в середине -

Вот почему между предложениями секции есть точки, а между секциями текста - нет? Очень странная логика

2021-07-30 04:20 UTC, Masynchin requested changes
Все комменты выше

2021-07-30 10:30 UTC, bullbesh commented on persistence/keyboard.py
> +"""
Вам кажется

2021-07-30 10:30 UTC, bullbesh commented on persistence/main.py
> +- Помощь
"выводящий информацию", этого вполне достаточно

2021-07-30 10:56 UTC, Masynchin commented on persistence/main.py
> +    """
Ну и то, что выше к вакансиями

2021-07-30 15:00 UTC, Masynchin commented on persistence/main.py
> +    - Информация молодым специалистам)
Лишняя скобка

2021-07-30 15:03 UTC, Masynchin approved these changes

2021-07-30 15:04 UTC, merged